# Generated by Django 4.1.6 on 2023-02-10 01:30

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                ("diretor", models.CharField(max_length=100, verbose_name="Diretor")),
                ("genero", models.TextField(max_length=200, verbose_name="Genero")),
                ("like", models.IntegerField(default=0, verbose_name="Like")),
                ("deslike", models.IntegerField(default=0, verbose_name="Dislike")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        null=True,
                        upload_to=core.models.get_file_path,
                        variations={},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "link",
                    models.URLField(max_length=500, null=True, verbose_name="Link"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        default=models.CharField(max_length=100, verbose_name="Titulo"),
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "isfilme",
                    models.BooleanField(default=True, verbose_name="É um filme?"),
                ),
                ("download", models.IntegerField(default=0, verbose_name="Downloads")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("valor", models.IntegerField(null=True, verbose_name="Valor")),
                (
                    "qtd_max_telas",
                    models.IntegerField(
                        null=True, verbose_name="Quantidade maxima de telas"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "obra_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.obra",
                    ),
                ),
                ("duracao", models.IntegerField(default=0, verbose_name="Duracao")),
            ],
            options={
                "verbose_name": "Filme",
                "verbose_name_plural": "Filmes",
            },
            bases=("core.obra",),
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "obra_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.obra",
                    ),
                ),
                (
                    "qtd_temporadas",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade de temporadas"
                    ),
                ),
                (
                    "qtd_episodios",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade de episodios"
                    ),
                ),
            ],
            options={
                "verbose_name": "Serie",
                "verbose_name_plural": "Series",
            },
            bases=("core.obra",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
